ifndef::manversion[:manversion: 0.0.0]

= git-jot(1)
Matthieu Monsch <mtth@apache.org>
v{manversion}
:doctype: manpage
:manmanual: GIT-JOT
:mansource: GIT-JOT


== Name

git-jot - emulate branch-local notes


== Synopsis

[verse]
git-jot [-Eb BRANCH] [-n NAME]
git-jot -D [-ab BRANCH] [-n NAME]
git-jot -I [-ab BRANCH] [-l BRANCH | -fr REMOTE]
git-jot -L [-b BRANCH]
git-jot -P
git-jot -R [-tb BRANCH] [-n NAME]
git-jot -W [-b BRANCH] [-n NAME] PATH
git-jot -X [-afb BRANCH] [-r REMOTE]
git-jot -h


== Description

`git-jot` is a Bash script emulating `git-notes` functionality on branches.
It is particularly useful for https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows[branching workflows], allowing the user to add context to the feature under development.
Since it uses regular notes under the hood, they can be easily shared, unlike approaches based on branch descriptions.
These notes are tied to the branch's name, and will persist as commits get added, merged, rebased, etc.
Each branch can have multiple named jottings.
When no name is provided, `git-jot` operates on the `default` jotting for the branch.

Its workhorse command is `git jot` (short for `git jot -E`), which edits the default jotting for the current branch.
A typical development workflow looks like:

[source,console]
----
$ # Create a feature branch...
$ git jot # Open an editor to add notes to this feature branch
$ # Do some work: add commits, rebase, switch to another branch and back...
$ git jot # Update the previously created note
$ git jot -n review # Add a separate review jotting
$ # And so on...
----

Steps can be added to `git` hooks for additional automation.
For example the following `pre-push` hook can be used to always export a pushed branch's notes:

[source,shell]
----
hook() {
	git-jot -Xar "$1"
}
----

Other use-cases include using notes on the `main` branch to keep a running list of ideas.
This can be made even more convenient by introducing a few aliases, for example:

.`~/.config/git/config`
[source]
----
[alias]
  j = jot
  jm = jot -b main
----


== Options

`-D`::
Delete a branch jotting.
See also `-P` to remove notes corresponding to deleted branches.

`-E`::
Edit or create a branch jotting.
It will open an interactive editor, similar to `git-notes edit`.
This is the default command.

`-I`::
Import jottings from another local branch or a remote.
If neither `-l` nor `-r` is specified, the branch's upstream will be used as source.
All source jottings are imported.
Local imports copy jottings when the source branch still exists, and move them when it does not.

`-L`::
List all local jottings in `BRANCH`, `NAME`, and `UPDATED` columns, sorted by most recent update.
With `-b`, list jotting names for that branch.

`-P`::
Prune notes matching deleted branches.

`-X`::
Export branch jottings.
All branch jottings are exported.
If `-r` is not specified, the branch's default `push` remote will be used as target.
This command can be run within a `pre-push` hook to ensure the remote contains the latest version of the notes.

`-R`::
Read a branch jotting.
Its contents are printed to stdout.

`-W`::
Write a branch jotting from `PATH`.
If `PATH` is `-`, contents are read from stdin.

`-a`::
Return with a 0 exit code when no matching jotting was found.
By default deleting, exporting, or importing will fail if no matching jotting is found.
This can be useful for example to export notes from a hook.

`-b BRANCH`::
Name of the underlying branch.
Defaults to the currently active branch.

`-f`::
Allow non-fast-forward updates.

`-h`::
Show help message and exit.

`-l BRANCH`::
Name of the local branch to import jottings from.
This will overwrite matching jotting contents, if any.

`-n NAME`::
Name of the jotting to edit, delete, read, or write.
Defaults to `default`.
Names must be a single ref-safe path component and cannot contain `/`.

`-r REMOTE`::
Name of the remote to import jottings from.
The remote's branch name is assumed identical to the local target branch.
The current notes ref will be merged with the imported one, using the union strategy in case of any conflicts.

`-t`::
Show notes tree ref instead of contents.
This can be used to perform operations on the underlying notes, for example to view branch jottings history via `git log -p "$(git jot -Rt)"`.


== Implementation

Under the hood, `git-jot` performs the following actions to emulate branch-local jottings:

1. It creates a blob object unique to the target branch and jotting name,
2. It adds a reference to it of the form `refs/jottings/v1/blobs/$branch_name/$jotting_name` to access it later on,
3. It attaches all branch jottings to the above objects using a dedicated notes `ref` (`refs/notes/jottings/v1/$branch_name`).

Imported remote notes are namespaced by remote name (`refs/jottings/v1/remotes/$remote/notes/`).
Legacy refs from earlier versions are migrated into the v1 namespace automatically.
After v1 refs are written, older `git-jot` versions must be upgraded to see the updated jottings.


== See also

`git(1)`
`git-notes(1)`
`githooks(5)`
