ifndef::manversion[:manversion: 0.0.0]

= git-jot(1)
Matthieu Monsch <mtth@apache.org>
v{manversion}
:doctype: manpage
:manmanual: GIT-JOT
:mansource: GIT-JOT


== Name

git-jot - emulate branch-local notes


== Synopsis

[verse]
git-jot [-Eb BRANCH]
git-jot -D [-ab BRANCH]
git-jot -I [-aefb BRANCH] [-l BRANCH | -r REMOTE]
git-jot -L
git-jot -P
git-jot -V [-b BRANCH]
git-jot -X [-ab BRANCH] [-r REMOTE]
git-jot -h


== Description

`git-jot` is a Bash script emulating `git-notes` functionality on branches.
It is particularly useful for https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows[branching workflows], allowing the user to add context to the feature under development.
Since it uses regular notes under the hood, they can be easily shared, unlike approaches based on branch descriptions.
These notes are tied to the branch's name, and will persist as commits get added, merged, rebased, etc.

Its workhorse command is `git jot` (short for `git jot -E`), which edits a note specific to the current branch.
A typical development workflow looks like:

[source,console]
----
$ # Create a feature branch...
$ git jot # Open an editor to add notes to this feature branch
$ # Do some work: add commits, rebase, switch to another branch and back...
$ git jot # Update the previously created note
$ # And so on...
----

Steps can be added to `git` hooks for additional automation.
For example the following `pre-push` hook can be used to always export a pushed branch's notes:

[source,shell]
----
hook() {
	git-jot -Xar "$1"
}
----


== Options

`-D`::
Delete branch notes.
See also `-P` to remove notes corresponding to deleted branches.

`-E`::
Edit or create branch notes.
It will open an interactive editor, similar to `git-notes edit`.
This is the default command.

`-I`::
Import notes from another local branch or a remote.
If neither `-l` nor `-r` is specified, the branch's upstream will be used as source.

`-L`::
List all local branches with notes.

`-P`::
Prune notes matching deleted branches.

`-X`::
Export branch notes.
If `-r` is not specified, the branch's default `push` remote will be used as target.
This command can be run within a `pre-push` hook to ensure the remote contains the latest version of the notes.

`-V`::
View branch notes.
Its contents are printed to stdout.

`-a`::
Return with a 0 exit code when no branch note was found.
By default deleting, exporting, or importing will fail if no branch note is found.
This can be useful for example to export notes from a hook.

`-b BRANCH`::
Name of the underlying branch.
Defaults to the currently active branch.

`-e`::
Edit the note immediately after importing it.
This will open an editor, and save the edited version.

`-f`::
Allow non-fast-forward updates.

`-h`::
Show help message and exit.

`-l BRANCH`::
Name of the local branch to import the note from.

`-r REMOTE`::
Name of the remote to import the note from.
The remote's branch name is assumed identical to the local target branch.


== Implementation

Under the hood, `git-jot` performs the following actions to emulate a branch-local note:

1. It creates a blob object unique to the target branch,
2. It adds a reference to it of the form `/refs/jottings/$branch_name` to access it later on,
3. It attaches all branch notes to the above object using a dedicated notes `ref` (`/refs/notes/jottings/$branch_name`).

Note that all state is contained in `git`.


== See also

`git(1)`
`git-notes(1)`
`githooks(5)`
