name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
jobs:
  lint:
    name: Lint
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Lint
        run: shellcheck git-jot.sh
  tag:
    name: Tag
    timeout-minutes: 2
    runs-on: ubuntu-latest
    needs: lint
    permissions:
      contents: write
    outputs:
      new-version: ${{ steps.bump-version.outputs.new_version }}
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Bump version and create tag
        id: bump-version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  build-pages:
    name: Build GitHub Pages
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
      - name: Set up AsciiDoctor
        uses: reitzig/actions-asciidoctor@v2.0.2
        with:
          version: 2.0.18
      - name: Generate man page
        run: |
          curl https://mtth.github.io/d/asciidoctor.css \
            -o asciidoctor.css
          mkdir dist
          asciidoctor -b html git-jot.1.adoc \
            -a stylesheet=asciidoctor.css \
            -a manversion=${{ needs.tag.outputs.new-version }} \
            -o dist/index.html
      - name: Upload as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/
  deploy-pages:
    name: Deploy GitHub Pages
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: build-pages
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    permissions:
      id-token: write
      pages: write
    steps:
      - name: Deploy
        id: deploy
        uses: actions/deploy-pages@v4
