name: PR
on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Lint
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Lint
        run: shellcheck git-jot.sh
